### PR TITLE
Updates to the demo_mode ui_states

### PR DESCRIPTION
**Pull request by TaylorSmith28**
The code has been pushed to the physical titrator device and the LCD and Keypad are navigating through the UI_State. This PR has some of the changes to make the LCD and Keypad work as well as update the demo_mode ui_states.

### CODE REVIEW

**Comment by TaylorSmith28** [comment]
The DemoMode portion of the state machine should be discussed before this is merged.

**Comment by TaylorSmith28** [comment]
Updated the demo mode classes to allow for demo-ing of the physical devices

**Review by prestoncarman — CHANGES_REQUESTED** [review]
Can you separate the LCD.clear() changes into a separate PR?

**Comment by TaylorSmith28** [comment]
LCD.clear() has been moved to #100

**Review by prestoncarman — APPROVED** [review]
LGTM

**Pull request merged**
