### PR TITLE
Logger

### PR DESCRIPTION
**Pull request by TaylorSmith28**
Added a logger rather than print statements. Allows printing to a log file that will be generated after running the titration device.

### CODE REVIEW

**Comment by TaylorSmith28** [comment]
This PR fixes #51

**Comment by prestoncarman** [comment]
Can you add a test? Also does will this replace other print statements?

**Comment by TaylorSmith28** [comment]
Test has been added

**Comment by TaylorSmith28** [comment]
The implementation of this currently, is not necessary.

**Pull request closed without merging**
